apiVersion: v1
kind: Service
metadata:
  name: llm-rag-service
spec:
  type: NodePort
  selector:
    app: llm-rag-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31567  # Exposes on a fixed NodePort

